In [25]:
import numpy as np
import pandas as pd
import matplotlib.pyplot
import sklearn

In [26]:
df = pd.read_csv("data/train.csv")
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [27]:
a = df["Cabin"][0]
df.info()
df["no_cabin"] = (df["Cabin"].isnull())


from sklearn.preprocessing import LabelEncoder
label = LabelEncoder()
label.fit(["True","False"])
df["no_cabin"] = label.transform(df["no_cabin"])

label = LabelEncoder()
label.fit(["male","female"])
df["Sex"] = label.transform(df["Sex"])

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [28]:
df = df.join(pd.get_dummies(df["Cabin"],dtype=int))

In [29]:
df = df[df.columns.drop(["PassengerId","Name","SibSp","Ticket","Fare","Cabin","Embarked"])]
df = df.dropna()

In [30]:

df["Age"]=df["Age"].astype(int)
df.dtypes

Survived    int64
Pclass      int64
Sex         int64
Age         int64
Parch       int64
            ...
F33         int64
F38         int64
F4          int64
G6          int64
T           int64
Length: 153, dtype: object

In [31]:
df

,Survived,Pclass,Sex,Age,Parch,no_cabin,A10,A14,A16,A19,...,E8,F E69,F G63,F G73,F2,F33,F38,F4,G6,T
0,0,3,1,22,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,1,1,0,38,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,1,3,0,26,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,1,1,0,35,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,3,1,35,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
885,0,3,0,39,5,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
886,0,2,1,27,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
887,1,1,0,19,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
889,1,1,1,26,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
890,0,3,1,32,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [32]:
x = df[df.columns.drop(["Survived"])]
y = df["Survived"]

from sklearn.model_selection import train_test_split
xtrain , xtest , ytrain,ytest = train_test_split(x,y,test_size=0.2)

In [33]:
from sklearn.svm import SVC
model = SVC(C = 0.5,kernel="linear")
model.fit(xtrain,ytrain)

SVC(C=0.5, kernel='linear')

In [34]:
from sklearn.metrics import classification_report
yhat = model.predict(xtest)
print(classification_report(ytest,yhat))

              precision    recall  f1-score   support

           0       0.77      0.81      0.79        85
           1       0.70      0.64      0.67        58

    accuracy                           0.74       143
   macro avg       0.73      0.72      0.73       143
weighted avg       0.74      0.74      0.74       143

In [35]:
from sklearn.linear_model import LogisticRegression
model = LogisticRegression(solver= "saga",C = 0.5)
model.fit(xtrain,ytrain)

/usr/lib/python3.14/site-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(

LogisticRegression(C=0.5, solver='saga')

In [36]:

yhat = model.predict(xtest)
print(classification_report(ytest,yhat))

              precision    recall  f1-score   support

           0       0.74      0.89      0.81        85
           1       0.78      0.53      0.63        58

    accuracy                           0.75       143
   macro avg       0.76      0.71      0.72       143
weighted avg       0.75      0.75      0.74       143

In [37]:
from sklearn.tree import DecisionTreeClassifier
model = DecisionTreeClassifier(criterion = "gini")
model.fit(xtrain,ytrain)

DecisionTreeClassifier()

In [38]:
yhat = model.predict(xtest)
print(classification_report(ytest,yhat))

              precision    recall  f1-score   support

           0       0.77      0.86      0.81        85
           1       0.75      0.62      0.68        58

    accuracy                           0.76       143
   macro avg       0.76      0.74      0.75       143
weighted avg       0.76      0.76      0.76       143

In [39]:
from sklearn.ensemble import RandomForestClassifier
model = RandomForestClassifier(n_estimators=100)
model.fit(xtrain,ytrain)

RandomForestClassifier()

In [40]:
yhat = model.predict(xtest)
print(classification_report(ytest,yhat))

              precision    recall  f1-score   support

           0       0.77      0.80      0.79        85
           1       0.69      0.66      0.67        58

    accuracy                           0.74       143
   macro avg       0.73      0.73      0.73       143
weighted avg       0.74      0.74      0.74       143